### ISSUE TITLE
Health check path and ping/pong message

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io-dummy-client#1]
Is it supposed to get back pong message from server with client ping? In the code I can see there is a ping to sever by every 5 sec,  but I can't see the pong message from the server? Is there any documentation about the ping/pong mechanism of deepstream? 

And I saw there is a health check path in the server configuration, how does this related to ping/pong heartbeat? How we can utilize this path?

Thanks

**Comment by speedysera** [comment]
Just wondering if this issue is solved in version 5.1.1 of Deepstream.io?

**Comment by yasserf** [comment]
I believe so, there has been a fix fixes around health checks in v5.1

https://github.com/deepstreamIO/deepstream.io-client-js/commit/388506e9516374760b7c8710576d66ae6e59259b

**Comment by speedysera** [comment]
thanks!
